// Email Utilities for PRD Generator

/**
 * Create a mailto link with PRD content
 * @param {string[]} recipients - Array of email addresses
 * @param {string} prdContent - The PRD content
 * @param {object} formData - Form data for subject and body
 * @returns {string} mailto URL
 */
export const createMailtoLink = (recipients, prdContent, formData) => {
  const subject = encodeURIComponent(
    `PRD: ${formData.appName || 'Product Requirements Document'} - ${formData.prdVersion || '1.0'}`
  );

  // Create email body with summary and PRD content
  const body = encodeURIComponent(
    `Hello Team,

Please find below the Product Requirements Document for ${formData.appName || 'our project'}.

---
PROJECT OVERVIEW
---
App Name: ${formData.appName}
Platform: ${formData.platform}
Project Type: ${formData.projectType}
Due Date: ${formData.dueDate}

Target Audience:
- Demographics: ${formData.targetAudienceDemography.join(', ')}
- Geography: ${formData.targetAudienceGeography.join(', ')}

---
FULL PRD
---
${prdContent}

---
This PRD was generated using BuLLMake PRD Generator
Powered by ISTVON PRD Prompt Framework
`
  );

  // Build mailto URL
  const to = recipients.join(',');
  return `mailto:${to}?subject=${subject}&body=${body}`;
};

/**
 * Open mailto link to send PRD via email
 * @param {string[]} recipients - Array of email addresses
 * @param {string} prdContent - The PRD content
 * @param {object} formData - Form data
 */
export const sendPRDViaEmail = (recipients, prdContent, formData) => {
  if (!recipients || recipients.length === 0) {
    throw new Error('No recipients specified');
  }

  const mailtoLink = createMailtoLink(recipients, prdContent, formData);

  // Note: mailto links have character limits (~2000 chars for URL)
  // For long PRDs, we truncate and suggest attachment
  if (mailtoLink.length > 2000) {
    // Create shortened version
    const shortBody = encodeURIComponent(
      `Hello Team,

Please find attached the Product Requirements Document for ${formData.appName || 'our project'}.

PROJECT OVERVIEW
- App Name: ${formData.appName}
- Platform: ${formData.platform}
- Due Date: ${formData.dueDate}
- Version: ${formData.prdVersion || '1.0'}

The full PRD content is too large for email body. Please:
1. Download the PRD using the export options (PDF, DOC, or JSON)
2. Attach it to this email

This PRD was generated using BuLLMake PRD Generator.
`
    );

    const subject = encodeURIComponent(
      `PRD: ${formData.appName || 'Product Requirements Document'} - ${formData.prdVersion || '1.0'}`
    );
    const to = recipients.join(',');

    window.location.href = `mailto:${to}?subject=${subject}&body=${shortBody}`;

    return {
      truncated: true,
      message: 'PRD content was too long for email. Please attach the exported file.'
    };
  }

  window.location.href = mailtoLink;
  return { truncated: false, message: 'Email client opened successfully' };
};

/**
 * Validate email address format
 * @param {string} email - Email to validate
 * @returns {boolean}
 */
export const isValidEmail = (email) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

/**
 * Parse comma-separated emails
 * @param {string} input - Comma-separated email string
 * @returns {string[]} Array of valid emails
 */
export const parseEmails = (input) => {
  return input
    .split(/[,;\s]+/)
    .map(e => e.trim())
    .filter(e => isValidEmail(e));
};

/**
 * Copy PRD content to clipboard
 * @param {string} prdContent - The PRD content
 * @param {object} formData - Form data for header
 * @returns {Promise<boolean>}
 */
export const copyPRDToClipboard = async (prdContent, formData) => {
  const fullContent = `Product Requirements Document
${formData.appName || 'Application'}
Version ${formData.prdVersion || '1.0'} | ${new Date().toLocaleDateString()}

${prdContent}

---
Powered by ISTVON PRD Prompt Framework
Generated by BuLLMake PRD Generator`;

  try {
    await navigator.clipboard.writeText(fullContent);
    return true;
  } catch (err) {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = fullContent;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();

    try {
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    } catch (e) {
      document.body.removeChild(textarea);
      return false;
    }
  }
};
